server:
  port: 8003
spring:
  application:
    name: departmentProvider

  datasource:
    username: root
    password: pass
    url: jdbc:mysql://localhost:3306/spring_cloud_demo3?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_bin&useServerPrepStmts=false&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fan.api.entity
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka  #这个地址是 7001注册中心在 application.yml 中暴露出来额注册地址
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/ # 本地搭建的集群 需要修改hosts文件 /etc/hosts
  instance:
    instance-id: spring-cloud-provider-8003 #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址